services:
  mysql:
    container_name: review-mysql
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=review_db'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
    volumes:
      - './docker/mysql:/var/lib/mysql'